# Generated by Django 6.0.3 on 2026-03-26 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad', '0002_notapersonal_preguntaduda_subrayado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='versiculocompartido',
            options={'ordering': ['-fecha_creacion']},
        ),
        migrations.AlterField(
            model_name='versiculocompartido',
            name='libro',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='versiculocompartido',
            name='nota_publica',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='versiculocompartido',
            name='texto_biblico',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='versiculocompartido',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versiculos_compartidos', to=settings.AUTH_USER_MODEL),
        ),
    ]
